name: Release

permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

on:
  push:
    tags:
      - '*'

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch all history, including tags
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5.1.0
      with:
        version: '~> v1'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate build provenance attestations
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: '${{ github.workspace }}/dist/*'
